FROM wordpress:6.0.3-php7.4-apache

WORKDIR /var/www/html

COPY --chown=www-data:www-data ./configs/theme/directto /var/www/html/wp-content/themes/directto
COPY --chown=www-data:www-data ./configs/uploads /var/www/html/wp-content/uploads

RUN chmod 766 -R /var/www/html/wp-content/

EXPOSE 80

CMD ["apache2-foreground"]