version: '3'

services:
  db:
    container_name: directto-mysql
    image: mysql:8.0
    volumes:
      - directto-db-data:/var/lib/mysql
      - ./configs/db:/docker-entrypoint-initdb.d
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DB}
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - ${MYSQL_PORT}:3306
    networks:
      - directto-network
  
  wordpress:
    container_name: directto-wordpress
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - db
    ports:
      - ${WP_PORT}:80
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DB}
    volumes:
      - directto-wp-data:/var/www/html
      - ./configs/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - directto-network
  
  phpmyadmin:
    container_name: directto-phpmyadmin
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    env_file: .env
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - directto-network
    
volumes:
  directto-db-data:
  directto-wp-data:
   
networks:
  directto-network: